const messages: Record<string, string[]> = {
  en: ['Confirm current price with the business', 'Editorial listing; photos are illustrative. Availability, prices and business participation are not verified.', 'Booking request', 'This is a request, not a confirmed reservation. Price, availability and payment terms require separate confirmation. No payment is collected here.', 'Choose today or a future date.', 'Sending…', 'Download request summary', 'Request summary — not a ticket', 'Enter the lead guest name.', 'Sign in to send your request.', 'Account service unavailable. Your request has not been sent.'],
  tr: ['Güncel fiyatı işletmeyle doğrulayın', 'Editoryal liste; fotoğraflar temsilidir. Müsaitlik, fiyatlar ve işletmenin katılımı doğrulanmamıştır.', 'Rezervasyon talebi', 'Bu bir taleptir, kesinleşmiş rezervasyon değildir. Fiyat, müsaitlik ve ödeme koşulları ayrıca doğrulanmalıdır. Burada ödeme alınmaz.', 'Bugünü veya gelecek bir tarihi seçin.', 'Gönderiliyor…', 'Talep özetini indir', 'Talep özeti — bilet değildir', 'Misafirin adını ve soyadını girin.', 'Talep göndermek için giriş yapın.', 'Hesap hizmetine ulaşılamıyor. Talebiniz gönderilmedi.'],
  de: ['Aktuellen Preis beim Anbieter bestätigen', 'Redaktionelle Liste; Fotos dienen der Illustration. Verfügbarkeit, Preise und Teilnahme des Anbieters sind nicht bestätigt.', 'Buchungsanfrage', 'Dies ist eine Anfrage, keine bestätigte Buchung. Preis, Verfügbarkeit und Zahlungsbedingungen müssen separat bestätigt werden. Hier erfolgt keine Zahlung.', 'Heute oder ein zukünftiges Datum wählen.', 'Wird gesendet…', 'Anfrage herunterladen', 'Anfrageübersicht — kein Ticket', 'Namen des Hauptgastes eingeben.', 'Zum Senden bitte anmelden.', 'Kontodienst nicht verfügbar. Anfrage nicht gesendet.'],
  fr: ['Confirmez le tarif actuel avec le prestataire', 'Liste éditoriale ; photos illustratives. Disponibilité, tarifs et participation du prestataire non vérifiés.', 'Demande de réservation', 'Ceci est une demande, pas une réservation confirmée. Prix, disponibilité et paiement nécessitent une confirmation séparée. Aucun paiement ici.', 'Choisissez aujourd’hui ou une date future.', 'Envoi…', 'Télécharger la demande', 'Résumé de demande — pas un billet', 'Saisissez le nom du voyageur principal.', 'Connectez-vous pour envoyer la demande.', 'Service de compte indisponible. Demande non envoyée.'],
  ar: ['تحقق من السعر الحالي مع المنشأة', 'قائمة تحريرية؛ الصور توضيحية. لم يتم التحقق من التوفر أو الأسعار أو مشاركة المنشأة.', 'طلب حجز', 'هذا طلب وليس حجزًا مؤكدًا. يجب تأكيد السعر والتوفر وشروط الدفع بشكل منفصل. لا يتم تحصيل أي دفع هنا.', 'اختر اليوم أو تاريخًا مستقبليًا.', 'جارٍ الإرسال…', 'تنزيل ملخص الطلب', 'ملخص طلب — ليس تذكرة', 'أدخل اسم الضيف الرئيسي.', 'سجل الدخول لإرسال الطلب.', 'خدمة الحساب غير متاحة. لم يُرسل الطلب.'],
  ru: ['Уточните текущую цену у поставщика', 'Редакционная подборка; фото иллюстративные. Наличие, цены и участие компании не проверены.', 'Запрос бронирования', 'Это запрос, а не подтверждённая бронь. Цена, наличие и условия оплаты требуют отдельного подтверждения. Здесь оплата не взимается.', 'Выберите сегодня или будущую дату.', 'Отправка…', 'Скачать запрос', 'Сводка запроса — не билет', 'Введите имя основного гостя.', 'Войдите для отправки запроса.', 'Сервис аккаунта недоступен. Запрос не отправлен.'],
  zh: ['请向商家确认当前价格', '编辑推荐列表；图片仅供参考。尚未核实余位、价格或商家是否参与。', '预订申请', '这是申请，不是已确认的预订。价格、余位和付款条件须另行确认。此处不收款。', '请选择今天或未来日期。', '正在发送…', '下载申请摘要', '申请摘要 — 不是门票', '请输入主要旅客姓名。', '请登录后提交申请。', '账户服务不可用，申请未发送。'],
};
export const bookingText = (lang: string, index: number) => (messages[lang] ?? messages.en)[index];
const form: Record<string, string[]> = {
 en: ['Lead guest full name','Visit date','Request submitted','Not confirmed','Reference code','Place / experience','Done','Close','Price / payment','Request recorded. This is not confirmation from the business.'],
 tr: ['Misafirin adı soyadı','Ziyaret tarihi','Talep kaydedildi','Onaylanmadı','Referans kodu','Mekân / deneyim','Tamam','Kapat','Fiyat / ödeme','Talep kaydedildi. Bu, işletmenin rezervasyonu onayladığı anlamına gelmez.'],
 de: ['Name des Hauptgastes','Besuchsdatum','Anfrage gespeichert','Nicht bestätigt','Referenznummer','Ort / Erlebnis','Fertig','Schließen','Preis / Zahlung','Anfrage gespeichert. Dies ist keine Bestätigung des Anbieters.'],
 fr: ['Nom du voyageur principal','Date de visite','Demande enregistrée','Non confirmé','Référence','Lieu / expérience','Terminé','Fermer','Prix / paiement','Demande enregistrée. Ce n’est pas une confirmation du prestataire.'],
 ar: ['اسم الضيف الرئيسي','تاريخ الزيارة','تم تسجيل الطلب','غير مؤكد','رقم المرجع','المكان / التجربة','تم','إغلاق','السعر / الدفع','تم تسجيل الطلب. هذا ليس تأكيدًا من المنشأة.'],
 ru: ['Имя основного гостя','Дата посещения','Запрос сохранён','Не подтверждено','Номер запроса','Место / впечатление','Готово','Закрыть','Цена / оплата','Запрос сохранён. Это не подтверждение от компании.'],
 zh: ['主要旅客姓名','到访日期','申请已记录','尚未确认','参考编号','地点 / 体验','完成','关闭','价格 / 付款','申请已记录。这不代表商家已确认预订。'],
};
export const bookingLabel = (lang: string, index: number) => (form[lang] ?? form.en)[index];
