const cityTransportCopy:Record<string,Record<string,string>>={
  İstanbul:{en:'Use the official Metro İstanbul, İETT, Marmaray and Şehir Hatları pages to check routes, transfers and departure times.',tr:'Hat, aktarma ve kalkış saatlerini Metro İstanbul, İETT, Marmaray ve Şehir Hatları’nın resmî sayfalarından kontrol edin.',de:'Prüfen Sie Linien, Umstiege und Abfahrten auf den offiziellen Seiten von Metro İstanbul, İETT, Marmaray und Şehir Hatları.',fr:'Consultez les sites officiels de Metro İstanbul, İETT, Marmaray et Şehir Hatları pour les lignes, correspondances et départs.',ar:'راجع مواقع مترو إسطنبول وİETT ومرمراي وŞehir Hatları الرسمية لمعرفة الخطوط والتحويلات ومواعيد الانطلاق.',ru:'Маршруты, пересадки и отправления проверяйте на официальных сайтах Metro İstanbul, İETT, Marmaray и Şehir Hatları.',zh:'请通过 Metro İstanbul、İETT、Marmaray 和 Şehir Hatları 官网查询线路、换乘及发车时间。'},
  Ankara:{en:'Check EGO for city bus, metro and ANKARAY routes and departure times.',tr:'Şehir içi otobüs, metro ve ANKARAY hatları ile kalkış saatlerini EGO’dan kontrol edin.',de:'Linien und Abfahrten von Stadtbussen, Metro und ANKARAY finden Sie bei EGO.',fr:'Consultez EGO pour les lignes et horaires des bus, du métro et d’ANKARAY.',ar:'راجع EGO لمعرفة خطوط ومواعيد حافلات المدينة والمترو وANKARAY.',ru:'Линии и расписания городских автобусов, метро и ANKARAY проверяйте у EGO.',zh:'请通过 EGO 查询市内公交、地铁和 ANKARAY 的线路与发车时间。'},
  Antalya:{en:'Check Antalyakart for tram and bus connections. Confirm the nearest stop to your destination before travelling.',tr:'Tramvay ve otobüs bağlantıları için Antalyakart’ı kontrol edin. Yola çıkmadan önce gideceğiniz yere en yakın durağı belirleyin.',de:'Prüfen Sie Straßenbahn- und Busverbindungen bei Antalyakart und die nächstgelegene Haltestelle vor der Fahrt.',fr:'Consultez Antalyakart pour le tramway et les bus. Vérifiez l’arrêt le plus proche de votre destination avant de partir.',ar:'راجع Antalyakart لخطوط الترام والحافلات، وتأكد من أقرب محطة إلى وجهتك قبل السفر.',ru:'Проверяйте трамвайные и автобусные маршруты в Antalyakart. Заранее уточните ближайшую к месту назначения остановку.',zh:'请通过 Antalyakart 查询有轨电车和公交线路，出发前确认距离目的地最近的车站。'},
  İzmir:{en:'Check the official Metro, ESHOT, İZBAN and İZDENİZ pages for connections, departures and payment options.',tr:'Bağlantılar, kalkışlar ve ödeme seçenekleri için Metro, ESHOT, İZBAN ve İZDENİZ’in resmî sayfalarını kontrol edin.',de:'Verbindungen, Abfahrten und Zahlungsmöglichkeiten finden Sie auf den offiziellen Seiten von Metro, ESHOT, İZBAN und İZDENİZ.',fr:'Consultez les sites officiels du métro, d’ESHOT, d’İZBAN et d’İZDENİZ pour les correspondances, départs et paiements.',ar:'راجع المواقع الرسمية للمترو وESHOT وİZBAN وİZDENİZ لمعرفة التحويلات والمواعيد ووسائل الدفع.',ru:'Пересадки, отправления и способы оплаты уточняйте на официальных сайтах Metro, ESHOT, İZBAN и İZDENİZ.',zh:'请通过 Metro、ESHOT、İZBAN 和 İZDENİZ 官网查询换乘、发车时间及支付方式。'},
  Cappadocia:{en:'Plan transport for the particular town or valley you are visiting. Confirm local connections and return times with the operator.',tr:'Ulaşımı gideceğiniz kasaba veya vadiye göre planlayın. Yerel bağlantıları ve dönüş saatlerini işletmeciden teyit edin.',de:'Planen Sie die Fahrt für den jeweiligen Ort oder das Tal. Bestätigen Sie Verbindungen und Rückfahrzeiten beim Betreiber.',fr:'Organisez le trajet selon la ville ou la vallée visitée. Confirmez les liaisons locales et le retour auprès de l’opérateur.',ar:'خطط للتنقل حسب البلدة أو الوادي المقصود، وأكد المواصلات المحلية ومواعيد العودة مع المشغّل.',ru:'Планируйте транспорт до конкретного города или долины. Уточняйте местные рейсы и время возвращения у перевозчика.',zh:'请根据要前往的城镇或山谷安排交通，并向运营方确认当地接驳和返程时间。'},
}
export function cityTransportText(city:string,lang:string,fallback:string){return cityTransportCopy[city]?.[lang]??fallback}
export {cityTransportCopy}
