// title, explanation, name, email, phone, date, time, guests, note, send,
// date error, sign-in error, storage error, success. Keep the field set identical.
export const restaurantRequestCopy:Record<string,readonly string[]>={
  tr:['Rezervasyon talebi','SafeInTürkiye restoranı arayarak müsaitliği kontrol eder. Onay gelmeden rezervasyon kesinleşmez. İletişim bilgileriniz talebi yürütmek için kullanılır.','Ad soyad','E-posta','Telefon (ülke koduyla)','Tarih','Restoranın yerel saati','Kişi sayısı','Not (isteğe bağlı)','Talep gönder','Bugünü veya gelecek bir tarihi seçin.','Talep göndermek için önce hesabınıza giriş yapın.','Talep kaydedilemedi. Lütfen tekrar deneyin; rezervasyon henüz oluşturulmadı.','Talebiniz alındı. Ekibimiz restoranla görüşecek. Bu, kesinleşmiş rezervasyon değildir. Referans: '],
  en:['Reservation request','SafeInTürkiye will call the restaurant to check availability. Wait for confirmation before considering your table reserved. Your contact details are used to handle this request.','Full name','Email','Phone (with country code)','Date','Restaurant local time','Guests','Note (optional)','Send request','Please choose today or a future date.','Please sign in to your account before sending a request.','The request could not be saved. Please try again; no reservation has been made.','Request received. Our team will contact the restaurant. This is not a confirmed reservation. Reference: '],
  de:['Reservierungsanfrage','SafeInTürkiye ruft das Restaurant an, um die Verfügbarkeit zu prüfen. Ihre Reservierung gilt erst nach Bestätigung. Ihre Kontaktdaten werden zur Bearbeitung der Anfrage verwendet.','Vor- und Nachname','E-Mail','Telefon (mit Ländervorwahl)','Datum','Ortszeit des Restaurants','Personen','Anmerkung (optional)','Anfrage senden','Bitte wählen Sie heute oder ein zukünftiges Datum.','Bitte melden Sie sich an, bevor Sie eine Anfrage senden.','Die Anfrage konnte nicht gespeichert werden. Bitte versuchen Sie es erneut; es wurde keine Reservierung vorgenommen.','Anfrage eingegangen. Unser Team kontaktiert das Restaurant. Dies ist noch keine bestätigte Reservierung. Referenz: '],
  fr:['Demande de réservation','SafeInTürkiye appellera le restaurant pour vérifier les disponibilités. Votre réservation ne sera définitive qu’après confirmation. Vos coordonnées servent à traiter cette demande.','Nom complet','E-mail','Téléphone (avec indicatif du pays)','Date','Heure locale du restaurant','Nombre de personnes','Remarque (facultative)','Envoyer la demande','Choisissez aujourd’hui ou une date ultérieure.','Connectez-vous à votre compte avant d’envoyer une demande.','La demande n’a pas pu être enregistrée. Réessayez ; aucune réservation n’a été effectuée.','Demande reçue. Notre équipe contactera le restaurant. La réservation n’est pas encore confirmée. Référence : '],
  ar:['طلب حجز','سيتصل فريق SafeInTürkiye بالمطعم للتحقق من التوفر. لا يصبح الحجز نهائيًا إلا بعد التأكيد. تُستخدم بيانات الاتصال الخاصة بك لمعالجة هذا الطلب.','الاسم الكامل','البريد الإلكتروني','رقم الهاتف مع رمز الدولة','التاريخ','التوقيت المحلي للمطعم','عدد الأشخاص','ملاحظة (اختياري)','إرسال الطلب','يرجى اختيار اليوم أو تاريخ لاحق.','يرجى تسجيل الدخول إلى حسابك قبل إرسال الطلب.','تعذر حفظ الطلب. يرجى المحاولة مجددًا؛ لم يتم إجراء أي حجز.','تم استلام طلبك. سيتواصل فريقنا مع المطعم. هذا ليس حجزًا مؤكدًا بعد. الرقم المرجعي: '],
  ru:['Заявка на бронирование','Команда SafeInTürkiye позвонит в ресторан и уточнит наличие мест. Бронирование действительно только после подтверждения. Ваши контактные данные используются для обработки заявки.','Имя и фамилия','Электронная почта','Телефон (с кодом страны)','Дата','Местное время ресторана','Количество гостей','Примечание (необязательно)','Отправить заявку','Выберите сегодняшнюю или будущую дату.','Войдите в аккаунт, прежде чем отправлять заявку.','Не удалось сохранить заявку. Попробуйте ещё раз; бронирование не оформлено.','Заявка получена. Наша команда свяжется с рестораном. Бронирование ещё не подтверждено. Номер заявки: '],
  zh:['餐厅预订申请','SafeInTürkiye 团队将致电餐厅确认是否有空位。收到确认前，预订尚未生效。您的联系方式仅用于处理此次申请。','姓名','电子邮箱','电话号码（含国家区号）','日期','餐厅当地时间','人数','备注（选填）','提交申请','请选择今天或之后的日期。','请先登录您的账户，再提交申请。','申请未能保存。请重试；尚未完成任何预订。','已收到您的申请。我们的团队将联系餐厅。预订尚未确认。申请编号：'],
}
