export const toursLabel = (lang:string) => ({en:'Tours & experiences',tr:'Turlar ve deneyimler',de:'Touren & Erlebnisse',fr:'Excursions et expériences',ar:'الجولات والتجارب',ru:'Экскурсии и впечатления',zh:'旅游与体验',es:'Excursiones y experiencias'}[lang] ?? 'Tours & experiences')

// Same filter semantics in every supported interface language.
const filters: Record<string,string[]> = {
 en:['Sort by','Viator recommendations','Price: low to high','Price: high to low','Traveler rating','Minimum price','Maximum price','Duration','Any','Up to 4 hours','4–24 hours','Multi-day','Minimum rating','Travel date (optional)','Private tour','Free cancellation','Skip the line','Currency','Reset filters','Results','Final price, options and availability are confirmed on Viator.','Read more','Show less'],
 tr:['Sıralama','Viator önerileri','Fiyat: düşükten yükseğe','Fiyat: yüksekten düşüğe','Gezgin puanı','En düşük fiyat','En yüksek fiyat','Süre','Tümü','4 saate kadar','4–24 saat','Birden fazla gün','En düşük puan','Gezi tarihi (isteğe bağlı)','Özel tur','Ücretsiz iptal','Sıra beklemeden giriş','Para birimi','Filtreleri sıfırla','Sonuç','Son fiyat, seçenekler ve müsaitlik Viator’da doğrulanır.','Devamını oku','Daha az göster'],
 es:['Ordenar por','Recomendaciones de Viator','Precio: de menor a mayor','Precio: de mayor a menor','Valoración de viajeros','Precio mínimo','Precio máximo','Duración','Cualquiera','Hasta 4 horas','4–24 horas','Varios días','Valoración mínima','Fecha del viaje (opcional)','Tour privado','Cancelación gratuita','Sin colas','Moneda','Restablecer filtros','Resultados','El precio final, las opciones y la disponibilidad se confirman en Viator.','Leer más','Mostrar menos'],
 de:['Sortieren nach','Viator-Empfehlungen','Preis aufsteigend','Preis absteigend','Gästebewertung','Mindestpreis','Höchstpreis','Dauer','Alle','Bis 4 Stunden','4–24 Stunden','Mehrtägig','Mindestbewertung','Reisedatum (optional)','Private Tour','Kostenlose Stornierung','Ohne Anstehen','Währung','Filter zurücksetzen','Ergebnisse','Endpreis, Optionen und Verfügbarkeit werden bei Viator bestätigt.','Mehr lesen','Weniger anzeigen'],
 fr:['Trier par','Recommandations Viator','Prix croissant','Prix décroissant','Note des voyageurs','Prix minimum','Prix maximum','Durée','Tous','Jusqu’à 4 heures','4–24 heures','Plusieurs jours','Note minimum','Date (facultatif)','Visite privée','Annulation gratuite','Coupe-file','Devise','Réinitialiser les filtres','Résultats','Le prix final, les options et la disponibilité sont confirmés sur Viator.','Lire la suite','Réduire'],
 ar:['ترتيب حسب','توصيات Viator','السعر: من الأقل للأعلى','السعر: من الأعلى للأقل','تقييم المسافرين','أقل سعر','أعلى سعر','المدة','الكل','حتى 4 ساعات','4–24 ساعة','عدة أيام','أقل تقييم','تاريخ الرحلة (اختياري)','جولة خاصة','إلغاء مجاني','تجاوز الطابور','العملة','إعادة ضبط الفلاتر','النتائج','يتم تأكيد السعر النهائي والخيارات والتوافر على Viator.','اقرأ المزيد','عرض أقل'],
 ru:['Сортировка','Рекомендации Viator','Цена: по возрастанию','Цена: по убыванию','Оценка путешественников','Минимальная цена','Максимальная цена','Длительность','Все','До 4 часов','4–24 часа','Несколько дней','Минимальная оценка','Дата поездки (необязательно)','Частная экскурсия','Бесплатная отмена','Без очереди','Валюта','Сбросить фильтры','Результаты','Итоговая цена, варианты и наличие подтверждаются на Viator.','Читать дальше','Свернуть'],
 zh:['排序','Viator 推荐','价格从低到高','价格从高到低','旅客评分','最低价格','最高价格','时长','不限','不超过4小时','4–24小时','多日行程','最低评分','旅行日期（可选）','私人行程','免费取消','免排队','货币','重置筛选','结果','最终价格、选项和可订情况以 Viator 为准。','展开介绍','收起'],
}
export const tourFilterCopy = (lang:string) => filters[lang] ?? filters.en
