const copy:Record<string,[string,string,string,string,string]>={
 tr:['Minibüs / dolmuş','Belirli güzergâhlarda paylaşımlı ulaşım sağlar. Google’da her hat ve durak görünmeyebilir; geliş saatini garanti kabul etme. Binmeden gideceğin yeri, ücreti ve son dönüş seferini sürücüye veya hareket noktasına sor. Nakit TL yaygındır; küçük para bulundur, ancak bazı hatlar kartlı sisteme bağlıdır.','Şehir içi otobüs','Belediye ve sisteme bağlı özel halk otobüsleri hat ve durak düzeniyle çalışır. Trafik nedeniyle geliş tahminleri değişebilir. Ulaşım kartı veya desteklenen temassız ödeme gerekebilir; her araçta nakit kabul edildiğini varsayma. Güncel hat, ödeme ve sefer bilgisi için seçtiğin şehrin resmî bağlantısını kullan.','İlçe ve turistik bölge hatları merkezden farklı olabilir; bölgesel kartın her araçta geçtiğini varsayma.'],
 en:['Minibus / dolmuş','Shared transport follows local routes. Not every line or stop appears on Google; arrival times are not guaranteed. Ask the driver or departure point about your destination, fare and last return service. Cash TRY is common: carry small notes, but some routes use transport cards.','City buses','Municipal and integrated private buses follow routes and stops. Traffic can affect arrival estimates. A transport card or supported contactless payment may be required; do not assume every vehicle accepts cash. Use the selected city’s official link for current routes, payment and schedules.','District and tourist-area services can differ from the city centre; do not assume one card works on every vehicle.'],
 de:['Minibus / Dolmuş','Sammeltaxis fahren lokale Routen. Nicht alle Linien oder Haltestellen stehen bei Google; Ankunftszeiten sind nicht garantiert. Ziel, Preis und letzte Rückfahrt beim Fahrer erfragen. Kleine TRY-Scheine mitnehmen; manche Linien nutzen Verkehrskarten.','Stadtbusse','Kommunale und integrierte private Busse nutzen Linien und Haltestellen. Verkehr beeinflusst Ankunftszeiten. Verkehrskarte oder unterstützte kontaktlose Zahlung kann nötig sein; Bargeld wird nicht überall akzeptiert. Aktuelle Angaben beim offiziellen Betreiber prüfen.','Verbindungen in Bezirken und Tourismusgebieten können abweichen. Eine Karte gilt nicht automatisch überall.'],
 fr:['Minibus / dolmuş','Transport partagé sur des itinéraires locaux. Toutes les lignes ne figurent pas sur Google et les arrivées ne sont pas garanties. Demandez la destination, le tarif et le dernier retour au conducteur. Prévoyez de petites coupures en TRY ; certaines lignes utilisent une carte.','Bus urbains','Les bus municipaux et privés intégrés suivent des lignes et arrêts. Le trafic peut modifier les arrivées. Une carte de transport ou un paiement sans contact compatible peut être requis ; les espèces ne sont pas acceptées partout. Consultez le lien officiel de la ville.','Les dessertes des districts et zones touristiques peuvent différer ; une carte ne fonctionne pas nécessairement partout.'],
 ar:['الميني باص / دولموش','نقل مشترك على مسارات محلية. قد لا تظهر جميع الخطوط والمحطات على Google ولا تُضمن أوقات الوصول. اسأل السائق عن الوجهة والأجرة وآخر رحلة عودة. النقد بالليرة شائع؛ احمل فئات صغيرة، لكن بعض الخطوط تستخدم بطاقات النقل.','حافلات المدينة','تعمل الحافلات البلدية والخاصة المدمجة على خطوط ومحطات. قد تؤثر حركة المرور على الوصول. قد تحتاج بطاقة نقل أو دفعًا لاتلامسيًا مدعومًا؛ لا تفترض قبول النقد دائمًا. راجع الرابط الرسمي للمدينة.','قد تختلف خدمات المناطق السياحية والأحياء عن المركز؛ لا تفترض صلاحية بطاقة واحدة لكل المركبات.'],
 ru:['Маршрутки / долмуш','Совместные поездки по местным маршрутам. Не все линии и остановки есть в Google; время прибытия не гарантируется. Уточните у водителя направление, цену и последний обратный рейс. Наличные TRY распространены, но некоторые линии используют транспортные карты.','Городские автобусы','Муниципальные и интегрированные частные автобусы следуют маршрутам и остановкам. Пробки влияют на прибытие. Может понадобиться транспортная карта или поддерживаемая бесконтактная оплата; наличные принимают не везде. Проверяйте официальный сайт города.','В районах и туристических зонах условия могут отличаться; одна карта не обязательно действует везде.'],
 zh:['小巴 / dolmuş','沿当地线路运营的共享交通。Google 不一定包含所有线路和站点，到站时间不保证。上车前向司机确认目的地、票价和末班返程。现金里拉较常见，建议备好零钱，但部分线路使用交通卡。','市内公交车','市政及纳入统一系统的私营公交按线路和站点运行。交通状况会影响到站时间。可能需要交通卡或支持的非接触支付，不要假定每辆车都收现金。请通过所选城市的官方链接查看线路、支付方式和时刻表。','区县及旅游地区的服务可能与市中心不同，一张交通卡不一定适用于所有车辆。']
}
export default function LocalTransportTips({locale}:{locale:string}){const t=copy[locale]??copy.en;return <section className="grid gap-3 sm:grid-cols-2">{[0,2].map(i=><article key={i} className="rounded-2xl border border-sky-100 bg-white p-5"><h2 className="font-bold text-slate-900">{t[i]}</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">{t[i+1]}</p></article>)}<p className="text-sm text-slate-600 sm:col-span-2">{t[4]}</p></section>}
