const tips: Record<string,string[]> = {
 tr: ['Kalabalık yerlerde telefon, çanta ve cüzdanınızı kontrolünüzde tutun.', 'Tanımadığınız kişilerin içecek veya mekân davetlerine dikkat edin; içeceğinizi gözünüzün önünde tutun.', 'Resmî taksi kullanın, plakayı not edin ve taksimetrenin açılmasını isteyin.', 'Gösterilerden uzak durun; yerel makamların duyurularını ve ulaşım değişikliklerini takip edin.', 'Aktivite öncesi işletmeyi araştırın; güvenlik eğitimi, ekipman ve sigorta kapsamını kontrol edin.', 'Denizde yerel uyarılara uyun; çocukları gözetimsiz bırakmayın ve derinliği bilinmeyen suya atlamayın.'],
 en: ['Keep your phone, bag and wallet secure in crowded places.', 'Be cautious with invitations from strangers; keep your drink in sight.', 'Use registered taxis, note the plate and ask for the meter.', 'Avoid demonstrations; follow local announcements and transport changes.', 'Research activity providers; check safety instruction, equipment and insurance coverage.', 'Follow beach warnings, supervise children and never dive into water of unknown depth.'],
 de: ['Telefon, Tasche und Geldbörse im Gedränge sichern.', 'Bei Einladungen Fremder vorsichtig sein; Getränke im Blick behalten.', 'Registrierte Taxis nutzen, Kennzeichen notieren und Taxameter verlangen.', 'Demonstrationen meiden und lokale Hinweise beachten.', 'Anbieter, Sicherheitseinweisung, Ausrüstung und Versicherung prüfen.', 'Strandwarnungen beachten, Kinder beaufsichtigen und nicht in unbekanntes Wasser springen.'],
 fr: ['Gardez téléphone, sac et portefeuille en sécurité dans la foule.', 'Méfiez-vous des invitations inconnues ; gardez votre boisson en vue.', 'Utilisez les taxis enregistrés, notez la plaque et demandez le compteur.', 'Évitez les manifestations et suivez les annonces locales.', 'Vérifiez le prestataire, les consignes, le matériel et l’assurance.', 'Respectez les avertissements sur les plages, surveillez les enfants et ne plongez pas en eau inconnue.'],
 ar: ['احمِ هاتفك وحقيبتك ومحفظتك في الزحام.', 'احذر دعوات الغرباء واحتفظ بمشروبك أمام نظرك.', 'استخدم تاكسي مسجلًا وسجّل اللوحة واطلب تشغيل العداد.', 'ابتعد عن المظاهرات وتابع التعليمات المحلية.', 'تحقق من مقدم النشاط وإرشادات السلامة والمعدات والتأمين.', 'التزم بتحذيرات الشاطئ وراقب الأطفال ولا تقفز في مياه مجهولة العمق.'],
 ru: ['Следите за телефоном, сумкой и кошельком в толпе.', 'Осторожно относитесь к приглашениям незнакомцев; не оставляйте напиток без присмотра.', 'Используйте зарегистрированные такси, запишите номер и попросите счётчик.', 'Избегайте демонстраций и следите за местными объявлениями.', 'Проверьте организатора, инструктаж, оборудование и страховку.', 'Соблюдайте предупреждения на пляже, следите за детьми и не ныряйте в незнакомую воду.'],
 zh: ['在人群中保管好手机、包和钱包。', '谨慎对待陌生人的邀请，饮料不要离开视线。', '使用正规出租车，记下车牌并要求打表。', '避开示威活动，关注当地公告和交通变化。', '参加活动前核实运营方、安全培训、设备及保险。', '遵守海滩警示，看护儿童，不要跳入深度未知的水域。'],
};
export default function SafetyTips({lang}:{lang:string}) {
 return <section className="bg-white border border-sky-100 rounded-2xl p-5"><ul className="grid gap-4 sm:grid-cols-2">{(tips[lang]??tips.en).map((tip,index)=><li className="text-sm leading-relaxed flex gap-3" key={tip}><span aria-hidden="true">{['🎒','🥤','🚕','📢','🎟️','🏖️'][index]}</span>{tip}</li>)}</ul><a className="mt-5 inline-block text-xs text-blue-700 underline" href="https://www.gov.uk/foreign-travel-advice/turkey/safety-and-security" target="_blank" rel="noopener noreferrer">FCDO · Türkiye · 20.09.2026 ↗</a></section>
}
